#include "Peg.h"
#include "Input_Peg.h"
#include "Mastermind_game.h"
#pragma once

namespace Mastermind {

  using namespace System;
  using namespace System::ComponentModel;
  using namespace System::Collections;
  using namespace System::Windows::Forms;
  using namespace System::Data;
  using namespace System::Drawing;
  using namespace System::Collections::Generic;
  public ref class Game : public System::Windows::Forms::Form
  {
  public:
    Game(void);
    System::String^ username;
  protected:
    ~Game();
  private:
    int time;
    MastermindGame^ game;
    int row, column, info_row, info_column;
    cli::array<Input_Peg^, 1>^ color_buttons;
    cli::array<Peg^, 2>^ buttons;
    System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel1;
    System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel2;
    Peg^ button_12_1;
    Peg^ button_12_2;
    Peg^ button_12_3;
    Peg^ button_12_4;
    Peg^ button_11_1;
    Peg^ button_11_2;
    Peg^ button_11_3;
    Peg^ button_11_4;
    Peg^ button_10_1;
    Peg^ button_10_2;
    Peg^ button_10_3;
    Peg^ button_10_4;
    Peg^ button_9_1;
    Peg^ button_9_2;
    Peg^ button_9_3;
    Peg^ button_9_4;
    Peg^ button_8_1;
    Peg^ button_8_2;
    Peg^ button_8_3;
    Peg^ button_8_4;
    Peg^ button_7_1;
    Peg^ button_7_2;
    Peg^ button_7_3;
    Peg^ button_7_4;
    Peg^ button_6_1;
    Peg^ button_6_2;
    Peg^ button_6_3;
    Peg^ button_6_4;
    Peg^ button_5_1;
    Peg^ button_5_2;
    Peg^ button_5_3;
    Peg^ button_5_4;
    Peg^ button_4_2;
    System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel4;
    Input_Peg^ button_red;
    Input_Peg^ button_green;
    Input_Peg^ button_blue;
    Input_Peg^ button_yellow;
    Peg^ button_4_1;
    Peg^ button_4_3;
    Peg^ button_4_4;
    Peg^ button_3_1;
    Peg^ button_3_2;
    Peg^ button_3_3;
    Peg^ button_3_4;
    Peg^ button_2_1;
    Peg^ button_2_2;
    Peg^ button_2_3;
    Peg^ button_2_4;
    Peg^ button_1_1;
    Peg^ button_1_2;
    Peg^ button_1_3;
    Peg^ button_1_4;
    System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel3;
    Peg^ button_12_5;
    Peg^ button_12_6;
    Peg^ button_12_7;
    Peg^ button_12_8;
    Peg^ button_11_5;
    Peg^ button_11_6;
    Peg^ button_11_7;
    Peg^ button_11_8;
    Peg^ button_10_5;
    Peg^ button_10_6;
    Peg^ button_10_7;
    Peg^ button_10_8;
    Peg^ button_9_5;
    Peg^ button_9_6;
    Peg^ button_9_7;
    Peg^ button_9_8;
    Peg^ button_8_5;
    Peg^ button_8_6;
    Peg^ button_8_7;
    Peg^ button_8_8;
    Peg^ button_7_5;
    Peg^ button_7_6;
    Peg^ button_7_7;
    Peg^ button_7_8;
    Peg^ button_6_5;
    Peg^ button_6_6;
    Peg^ button_6_7;
    Peg^ button_6_8;
    Peg^ button_5_5;
    Peg^ button_5_6;
    Peg^ button_5_7;
    Peg^ button_5_8;
    Peg^ button_4_6;
    Peg^ button_4_5;
    Peg^ button_4_7;
    Peg^ button_4_8;
    Peg^ button_3_5;
    Peg^ button_3_6;
    Peg^ button_3_7;
    Peg^ button_3_8;
    Peg^ button_2_5;
    Peg^ button_2_6;
    Peg^ button_2_7;
    Peg^ button_2_8;
    Peg^ button_1_5;
    Peg^ button_1_6;
    Peg^ button_1_7;
    Peg^ button_1_8;
    Input_Peg^ button_purple;
    Input_Peg^ button_lime;
    Input_Peg^ button_cyan;
    Input_Peg^ button_orange;
    System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel5;
    System::Windows::Forms::Label^ label1;
    System::Windows::Forms::Timer^ timer1;
    System::Windows::Forms::Button^ button_quit;
    System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel6;
    System::ComponentModel::IContainer^ components;
    void InitializeComponent(void);
    System::Void timer1_Tick(System::Object^ sender, System::EventArgs^ e);
    System::Void Game_Load(System::Object^ sender, System::EventArgs^ e);
    System::Void button_quit_Click(System::Object^ sender, System::EventArgs^ e);
    System::Void Game_FormClosed(System::Object^ sender, System::Windows::Forms::FormClosedEventArgs^ e);
    System::Void ColorButton_Click(System::Object^ sender, System::EventArgs^ e);
  };
}
